version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development

    command: [/bin/sh, -c, sleep 5 && npm run ngrok-tg-webhook && npx nodemon src/index.js]

    environment:
      HOST: '0.0.0.0'
      PORT: 3000

    env_file: .docker.env

    ports:
      - 3000:3000

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok
    command: http app:3000
    ports:
      - 4040:4040

    env_file: .docker.env
