# TODO: also sum by team_id
groups:
  - name: em-metrics-dora
    interval: 1d
    # DORA
    # - Deployment Frequency
    # - Lead time for changes
    # - Change failure rate
    # - Time to restore
    rules:
      - record: em_dora_deployment_frequency_daily
        # nb of deployments in the day
        expr: rate(deployment_frequency_total[1d]) * 60 * 60 * 24

      - record: em_dora_lead_time_for_changes_daily_bucket
        expr: sum by (le, environment) (rate(lead_time_for_changes_minute_bucket[1d]))

      - record: em_dora_change_failure_rate_daily
        expr: sum by (environment) (change_failure_count_deployment_total) / sum by (environment) (deployment_frequency_total)

      - record: em_dora_time_to_restore_daily_bucket
        expr: sum by (le, environment) (rate(time_to_restore_minute_bucket[1d]))

  - name: em-metrics-ticketing
    interval: 1d
    # Ticketing
    # - Time per ticket (per type)
    # - Time per ticket
    # - Estimation changes (hist + and hist -)
    rules:
        # Allows computing Innovation ratio by ticket_type
      - record: em_core4_ticketing_time_per_ticket_type_daily_sum
        expr: rate(time_per_ticket_minute_sum[1d]) * 60 * 60 * 24

      - record: em_ticketing_time_per_ticket_type_daily_bucket
        expr: sum by (le, environment, ticket_type) (rate(time_per_ticket_minute_bucket[1d]))

      - record: em_ticketing_time_per_ticket_daily_bucket
        expr: sum by (le, environment) (rate(time_per_ticket_minute_bucket[1d]))

      - record: em_ticketing_estimation_changes_positive_bucket
        expr: sum by (le, environment) (rate(ticket_estimation_changed_points_bucket[1d]))

      - record: em_ticketing_estimation_changes_negative_bucket
        expr: sum by (le, environment) (rate(ticket_estimation_changed_negative_points_bucket[1d]))

  - name: em-metrics-pull-requests
    interval: 1d
    rules:
      # Core4
      - record: em_core4_pull_requests_merged_frequency_daily
        expr: rate(pull_request_merged_count_pull_requests_total[1d]) * 60 * 60 * 24

      - record: em_pull_requests_opened_frequency_daily
        expr: rate(pull_request_opened_count_pull_requests_total[1d]) * 60 * 60 * 24

      - record: em_pull_requests_closed_frequency_daily
        expr: rate(pull_request_closed_count_pull_requests_total[1d]) * 60 * 60 * 24

      - record: em_pull_request_loc_added_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_loc_added_lines_of_code_bucket[1d]))

      - record: em_pull_request_loc_removed_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_loc_removed_lines_of_code_bucket[1d]))

      - record: em_pull_request_nb_reviews_per_pr_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_nb_reviews_per_pr_bucket[1d]))

      - record: em_pull_request_nb_comments_per_review_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_nb_comments_per_review_comments_bucket[1d]))

      - record: em_pull_request_time_to_first_review_minutes_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_time_to_first_review_minutes_minute_bucket[1d]))

      - record: em_pull_request_time_to_approve_minutes_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_time_to_approve_minutes_minute_bucket[1d]))

      - record: em_pull_request_time_to_merge_minutes_daily_bucket
        expr: sum by (le, team_id) (rate(pull_request_time_to_merge_minutes_minute_bucket[1d]))

