- name: Homelab
  # slug: /
  width: default
  head_widgets: []

  columns:
    - size: small
      widgets: 
        - type: monitor
          show-failing-only: false
          sites:
            - title: EM Metrics
              url: https://em.jocolina.com/health
              icon: /assets/control-logo.png

    - size: full
      widgets:
        - type: split-column
          widgets:
            - type: group
              widgets:
                - type: reddit
                  subreddit: EngineeringManagers
                - type: reddit
                  subreddit: homelab
                - type: reddit
                  subreddit: minilab

            - type: hacker-news

    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: search
          search-engine: google
          new-tab: true
          placeholder: Google
          bangs: []
