name: Blog

on:
  push:
    branches:
      - master
    paths:
      - 'blog/**.*'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'blog/**.*'
  workflow_dispatch:

defaults:
  run:
    working-directory: blog

jobs:
  build_blog:
    name: 'Build & Publish blog'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Clone'
        uses: actions/checkout@main

      - name: 'Install Deps'
        run: npm i

      - name: 'Build'
        run: npm run build

      # Only run on push
      - name: 'Build & upload static files'
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: blog/_site

      - id: deployment
        name: Deploy
        uses: actions/deploy-pages@v1.2.4
