name: Lambda

on:
  release:
    types:
      - published

jobs:
  deploy_lambda:
    name: Deploy Lambda

    runs-on: ubuntu-latest

    # Redundant
    if: ${{ github.event_name == 'release' }}

    defaults:
      run:
        working-directory: lambda

    steps:
      - name: Install dependencies
        run: npm i

      - uses: jsmrcaga/action-easy-lambda-deploy@latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          function_name: github-readme-v2
          region: eu-west-3
