name: Plasma Bot

on:
  push:
    tags:
      - plasma-bot-v*
  pull_request:
    types: [opened, synchronize]

defaults:
  run:
    shell: bash
    working-directory: ./plasma-bot

jobs:
  build_and_push:
    name: Build & Push Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get docker tag from git tag
        id: tag
        env:
          VERSION_TAG: ${{ github.ref_name }}
          # removes everything up to dash (*-), so name-v1.2.3 => v1.2.3
        run: |
          #!/bin/bash

          set -e

          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "tag=jsmrcaga/plasma-bot:pull_request" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          version=${VERSION_TAG##plasma-bot-}
          tag="jsmrcaga/plasma-bot:${version}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - run: docker build -t ${{ steps.tag.outputs.tag }} .

      - name: Docker login
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        if: ${{ github.event_name == 'push' }}

      - run: docker push ${{ steps.tag.outputs.tag }}
        if: ${{ github.event_name == 'push' }}


