name: Readme

on:
  push:
    branches:
      - master

jobs:
  write_readme:
    name: 'Write Readme'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone'
        uses: actions/checkout@main
      - name: 'Deps'
        run: npm i
      - name: 'Write'
        run: node src/index.js
      - name: 'Commit'
        run: |
          git config user.name "Github Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README from GitHub action"
      - name: 'Push'
        run: git push -u origin master
